DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS role_authorities;
DROP TABLE IF EXISTS authorities;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS books;

CREATE TABLE authorities (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
username     VARCHAR(50)  NOT NULL,
password     VARCHAR(255) NOT NULL,
enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
email        VARCHAR(100) NOT NULL,
date_created TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT uk_users_username UNIQUE (username),
CONSTRAINT uk_users_email    UNIQUE (email)
);

CREATE TABLE role_authorities (
    role_id      BIGINT NOT NULL,
authority_id BIGINT NOT NULL,
PRIMARY KEY (role_id, authority_id),
CONSTRAINT fk_role_authorities_role
FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
CONSTRAINT fk_role_authorities_authority
FOREIGN KEY (authority_id) REFERENCES authorities(id) ON DELETE CASCADE
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
role_id BIGINT NOT NULL,
PRIMARY KEY (user_id, role_id),
CONSTRAINT fk_user_roles_user
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
CONSTRAINT fk_user_roles_role
FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE books (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title        VARCHAR(200) NOT NULL,
author       VARCHAR(120) NOT NULL,
isbn         VARCHAR(20)  NOT NULL,
price        NUMERIC(10,2) NOT NULL DEFAULT 0.00,
in_stock     BOOLEAN      NOT NULL DEFAULT TRUE,
date_created TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT uk_books_isbn UNIQUE (isbn)
);